Repository AdityaSinha2305/ForkTheCaptcha, pull requests merged in 2024-10, with the labels that each got.

#11 ISSUE#9 Make submit button responsive
  js/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#12 bg added in html
  index.html
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#21 fixed the issue resetting input box when the captcha gets reset
  js/script.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#29 Added a event listener when keydown is Enter
  js/script.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#39 feat: Add responsive behaviour
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#47 New branch nav bar complete
  index.html
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#45 Reload the captcha for every 25seconds
  js/script.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2024

#55 Added Styles to the alert
  index.html
  js/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#62 Add footer to home page
  index.html
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#81 fix: toggle styling
  index.html
  package-lock.json
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest, gssoc-ext, level1

#40 added login page redirect after submitting captcha
  js/script.js
  login.html
  styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest
